### ISSUE TITLE
ImportError: No module named payu

### ISSUE THREAD

**Issue by KingOlami** [SalahAdDin/django-oscar-payu#3]
I ran python manage.py migrate and got the error

`Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Olar/Documents/Dev/Python/oscars/dev/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/Olar/Documents/Dev/Python/oscars/dev/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/Olar/Documents/Dev/Python/oscars/dev/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Olar/Documents/Dev/Python/oscars/dev/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Olar/Documents/Dev/Python/oscars/dev/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named payu`

**Comment by KingOlami** [comment]
any fix for this

**Comment by SalahAdDin** [comment]
Wow, it's my first issue, thank you!!!
if i'm not wrong you have to add it in the applications by `django-oscar-payu`.

**Comment by rahulmohite228** [comment]
The same issues i have faced! Any solution for it?

**Comment by rm08** [comment]
The same issues i have face! Find any solution?

**Comment by MsMansiDhruv** [comment]
Was anyone able to solve this? I am facing this issue while integrating PayU with my project.

**Comment by SalahAdDin** [comment]
we are welcoming to any PR.

**Comment by Mrooie** [comment]
@SalahAdDin Hey! :D
There is no "payu" module in site packages. :D Everything installs as django-oscar-payu. :)
I don't really know how to rename package, but I guess that would fix all :P

**Comment by SalahAdDin** [comment]
@Mrooie You can try to make a PR, thanks.
